version: '3.8'

services:
  # Angular Frontend with Bootstrap 5.3.3 - WORKING VERSION
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      stock-prediction:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - stock-prediction-network
    labels:
      - "com.docker.compose.service=frontend"
      - "description=Bootstrap Angular Frontend"

  # Go Backend API with ML Prediction Service
  stock-prediction:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Backend on port 8081
    environment:
      # Server Configuration
      - SERVER_PORT=8081
      - SERVER_READ_TIMEOUT=30s
      - SERVER_WRITE_TIMEOUT=30s
      - LOG_LEVEL=info
      
      # Stock Configuration
      - STOCK_SYMBOL=NVDA
      - STOCK_LOOKBACK_DAYS=5
      - STOCK_BUY_THRESHOLD=1.01
      - STOCK_SELL_THRESHOLD=0.99
      
      # ML Configuration
      - ML_PYTHON_SCRIPT=scripts/ml/predict.py
      - ML_MODEL_PATH=/app/persistent_data/ml_models/nvda_lstm_model
      - ML_PREDICTION_TTL=5m
      - STOCK_DATA_CACHE_PATH=/app/persistent_data/stock_data/cache
      
      # Cache Configuration
      - REDIS_URL=redis://redis:6379
      - CACHE_TTL=300
      - CACHE_MAX_SIZE=1000
      
      # CORS Configuration
      - CORS_ORIGINS=*
    volumes:
      - ./persistent_data:/app/persistent_data
      - ./scripts:/app/scripts:ro
      - ./models:/app/models:ro
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - stock-prediction-network
    labels:
      - "com.docker.compose.service=backend"
      - "description=Go Backend with ML Engine"

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - ./persistent_data/redis:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - stock-prediction-network
    labels:
      - "com.docker.compose.service=cache"

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./persistent_data/prometheus:/prometheus
    depends_on:
      - stock-prediction
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - stock-prediction-network
    labels:
      - "com.docker.compose.service=monitoring"

  # Grafana Dashboards
  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./persistent_data/grafana:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    depends_on:
      prometheus:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stock-prediction-network
    user: "472:472"
    labels:
      - "com.docker.compose.service=visualization"

# Networks
networks:
  stock-prediction-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16

# Volumes (using simple local volumes)
volumes:
  persistent_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  redis_data:
    driver: local
